### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by zhoukk** [zhoukk/zhoukk.github.io#6]
upgrade:
```
kubeadm upgrade plan
kubeadm upgrade apply v1.13.4
```

reset:
```
kubeadm reset
systemctl stop kubelet
systemctl stop docker
rm -rf /var/lib/cni/
rm -rf /var/lib/kubelet/*
rm -rf /etc/cni/
ifconfig cni0 down
ifconfig flannel.1 down
ifconfig docker0 down
ip link delete cni0
ip link delete flannel.1
systemctl start docker
```

k8s-init.sh
```
#!/bin/bash

set -x

cat <<EOF >>  /etc/hosts
192.168.1.99 srv01
192.168.1.98 srv02
192.168.1.97 srv03
EOF

yum install -y vim net-tools

setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
systemctl disable firewalld --now

yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2

yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum-config-manager \
    --add-repo \
    http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-cli containerd.io

mkdir -p /etc/docker
tee /etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": ["https://so4p5nnk.mirror.aliyuncs.com"],
  "graph": "/data/docker"
}
EOF

systemctl enable docker --now

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
EOF

yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
vm.swappiness = 0
EOF

sysctl --system
modprobe br_netfilter
swapoff -a
sed -i -e '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

docker pull mirrorgooglecontainers/kube-apiserver:v1.14.0
docker pull mirrorgooglecontainers/kube-controller-manager:v1.14.0
docker pull mirrorgooglecontainers/kube-scheduler:v1.14.0
docker pull mirrorgooglecontainers/kube-proxy:v1.14.0

docker pull mirrorgooglecontainers/pause:3.1
docker pull mirrorgooglecontainers/etcd:3.3.10
docker pull coredns/coredns:1.3.1

docker tag mirrorgooglecontainers/kube-apiserver:v1.14.0 k8s.gcr.io/kube-apiserver:v1.14.0
docker tag mirrorgooglecontainers/kube-controller-manager:v1.14.0 k8s.gcr.io/kube-controller-manager:v1.14.0
docker tag mirrorgooglecontainers/kube-scheduler:v1.14.0 k8s.gcr.io/kube-scheduler:v1.14.0
docker tag mirrorgooglecontainers/kube-proxy:v1.14.0  k8s.gcr.io/kube-proxy:v1.14.0

docker tag mirrorgooglecontainers/pause:3.1  k8s.gcr.io/pause:3.1
docker tag mirrorgooglecontainers/etcd:3.3.10  k8s.gcr.io/etcd:3.3.10
docker tag coredns/coredns:1.3.1 k8s.gcr.io/coredns:1.3.1

docker rmi mirrorgooglecontainers/kube-apiserver:v1.14.0
docker rmi mirrorgooglecontainers/kube-controller-manager:v1.14.0
docker rmi mirrorgooglecontainers/kube-scheduler:v1.14.0
docker rmi mirrorgooglecontainers/kube-proxy:v1.14.0

docker rmi mirrorgooglecontainers/pause:3.1
docker rmi mirrorgooglecontainers/etcd:3.3.10
docker rmi coredns/coredns:1.3.1

docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1
docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1 gcr.io/kubernetes-helm/tiller:v2.13.1
docker rmi registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1

docker pull mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.1
docker tag mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.1 k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
docker rmi  mirrorgooglecontainers/kubernetes-dashboard-amd64:v1.10.1

docker pull mirrorgooglecontainers/defaultbackend:1.4
docker tag mirrorgooglecontainers/defaultbackend:1.4 k8s.gcr.io/defaultbackend:1.4
docker rmi mirrorgooglecontainers/defaultbackend:1.4

docker pull mirrorgooglecontainers/metrics-server-amd64:v0.3.1
docker tag mirrorgooglecontainers/metrics-server-amd64:v0.3.1 gcr.io/google_containers/metrics-server-amd64:v0.3.1
docker rmi mirrorgooglecontainers/metrics-server-amd64:v0.3.1

docker pull mirrorgooglecontainers/heapster:v1.5.2
docker tag mirrorgooglecontainers/heapster:v1.5.2 k8s.gcr.io/heapster:v1.5.2
docker rmi mirrorgooglecontainers/heapster:v1.5.2

docker pull mirrorgooglecontainers/addon-resizer:1.7
docker tag mirrorgooglecontainers/addon-resizer:1.7 k8s.gcr.io/addon-resizer:1.7
docker rmi mirrorgooglecontainers/addon-resizer:1.7

docker pull googlecontainer/k8szk:v3
docker tag googlecontainer/k8szk:v3 gcr.io/google_samples/k8szk:v3
docker rmi googlecontainer/k8szk:v3

docker pull quay-mirror.qiniu.com/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0
docker tag quay-mirror.qiniu.com/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0 quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0
docker rmi quay-mirror.qiniu.com/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0

docker pull quay-mirror.qiniu.com/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
docker tag quay-mirror.qiniu.com/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11 quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
docker rmi quay-mirror.qiniu.com/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11

systemctl enable --now kubelet

```

k8s-master
```
#!/bin/bash

set -x

kubeadm init \
   --kubernetes-version=v1.14.0 \
   --pod-network-cidr=10.244.0.0/16 \
   --apiserver-advertise-address=$(hostname -i) \
   --apiserver-cert-extra-sans=$(hostname -i)

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl describe node srv01 | grep Taint
kubectl taint nodes srv01 node-role.kubernetes.io/master-

curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash

cat <<EOF >  helm-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF

kubectl create -f helm-rbac.yaml

helm init --service-account tiller --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts

cat <<EOF >  nginx-ingress-values.yaml
controller:
  service:
    externalIPs:
      - 192.168.1.99
EOF

helm install --name nginx-ingress --namespace kube-system stable/nginx-ingress -f nginx-ingress-values.yaml

kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/00-crds.yaml
kubectl label namespace kube-system certmanager.k8s.io/disable-validation=true
helm install --name cert-manager --namespace kube-system stable/cert-manager

cat <<EOF > letsencrypt-prod.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zhoukk@xxx.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
EOF

kubectl apply -f letsencrypt-prod.yaml


cat <<EOF >  kubernetes-dashboard-values.yaml
ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

  hosts:
    - k8s.internal.xxx.com

  tls:
    - secretName: kubernetes-dashboard-tls
      hosts:
        - k8s.internal.xxx.com

rbac:
  create: true
  clusterAdminRole: true
EOF

helm install --name kubernetes-dashboard --namespace kube-system stable/kubernetes-dashboard -f kubernetes-dashboard-values.yaml


cat <<EOF >  metrics-server-values.yaml
args:
  - --logtostderr
# enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP
EOF

helm install --name metrics-server --namespace kube-system stable/metrics-server -f metrics-server-values.yaml


helm install --name heapster --namespace kube-system stable/heapster


cat <<EOF >  grafana-values.yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - grafana.internal.xxx.com
  tls:
    - secretName: local-xxx-com-tls
      hosts:
        - grafana.internal.xxx.com

persistence:
  enabled: true

# Administrator credentials when not using an existing secret (see below)
adminUser: xxx
adminPassword: grafana@xxx

plugins: []
  #- digrich-bubblechart-panel
  #- grafana-clock-panel

## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
EOF

helm install --name grafana --namespace kube-system stable/grafana -f grafana-values.yaml


cat <<EOF > prometheus-values.yaml
alertmanager:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'

    hosts:
      - alert.internal.xxx.com

    tls:
      - secretName: prometheus-alerts-tls
        hosts:
          - alert.internal.xxx.com

server:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'

    hosts:
      - prometheus.internal.xxx.com

    tls:
      - secretName: prometheus-server-tls
        hosts:
          - prometheus.internal.xxx.com

pushgateway:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'

    hosts:
      - pushgateway.internal.xxx.com

    tls:
      - secretName: prometheus-alerts-tls
        hosts:
          - pushgateway.internal.xxx.com
EOF

helm install --name prometheus --namespace kube-system stable/prometheus -f prometheus-values.yaml


cat << EOF > prometheus-adapter-values.yaml
prometheus:
  url: http://prometheus-server.kube-system.svc
  port: 9090
EOF

helm install --name prometheus-adapter --namespace kube-system stable/prometheus-adapter -f prometheus-adapter-values.yaml


yum install -y nfs-utils

mkdir -p /data/nfs
chmod 777 /data/nfs

cat << EOF > /etc/exports
/data/nfs *(rw,sync,no_root_squash)
EOF

systemctl enable nfs-server --now

cat << EOF > nfs-client-provisioner-srv01-values.yaml
nfs:
  server: 192.168.1.99
  path: /data/nfs
  mountOptions:

storageClass:
  create: true

  # Set a provisioner name. If unset, a name will be generated.
  # provisionerName:

  # Set StorageClass as the default StorageClass
  # Ignored if storageClass.create is false
  defaultClass: true

  # Set a StorageClass name
  # Ignored if storageClass.create is false
  name: nfs-srv01

  # Allow volume to be expanded dynamically
  allowVolumeExpansion: true

  # Method used to reclaim an obsoleted volume
  reclaimPolicy: Delete

  # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
  archiveOnDelete: true
EOF

helm install --name nfs-client-provisioner-srv01 --namespace kube-system stable/nfs-client-provisioner -f nfs-client-provisioner-srv01-values.yaml

helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm install --name zookeeper incubator/zookeeper


```

image pull secret:
```
kubectl create secret docker-registry aliyun-docker-registry-secret --docker-server=registry.cn-shanghai.aliyuncs.com --docker-username=xxxxxx --docker-password=xxxxxx --docker-email=xxx@xxx.xxx
```
```
spec:
      imagePullSecrets:
      - name: aliyun-docker-registry-secret
      containers:
        image: registry.cn-shanghai.aliyuncs.com/xxxxxx
```
